### ISSUE TITLE
Conflict with all-the-icons-completion

### ISSUE THREAD

**Issue by mclearc** [bdarcus/bibtex-actions#166] opened 2021-07-07 17:18 UTC
**Describe the bug**
I use [https://github.com/iyefrat/all-the-icons-completion](https://github.com/iyefrat/all-the-icons-completion) to get icons with marginalia-mode enabled. This seems to conflict with using icons in bibtex-actions, however. If I disable all-the-icons-completion icons show up in bibtex-actions. 

**To Reproduce**
1. Enable `all-the-icons-completion-mode`
2. Run `bibtex-actions-open`
3. See error (i.e. no icons)

**Expected behavior**
icons should be in the prefix column

**Screenshots**

**Emacs version:**
28

**Additional context**

**Comment by bdarcus** [comment] 2021-07-07 17:29
Just to clarify:

1. Are you using the icon config listed on the README here?
2. Are you using this with the doom "selectrum" branch?

**Comment by mclearc** [comment] 2021-07-07 17:32
yes to (1) -- though I can get the same problem with simpler icon configs. And no to (2) -- I don't use doom.

**Comment by bdarcus** [comment] 2021-07-07 17:46
@iyefrat - do you see something wrong with the config I suggest on the README that would lead to some conflict with your package?

I don't have a specific subsection I can link to, but see [here](https://github.com/bdarcus/bibtex-actions#rich-ui), and the part that starts "Here’s how to configure it to use all-the-icons".

I suppose we could include this for the biblio module when people have the `+icons` flag set?

**Comment by iyefrat** [comment] 2021-07-07 18:32
The way `all-the-icons-completions` works is by advising `completion-metadata-get` to add icons when calling `affixation-function`. My best guess is that this conflicts somehow with the `affixation-function` logic in `bibtex-actions-read`. I'll have to try and look into it more to get more information. From what @mclearc says, I assume that this doesn't really have to do with icons, and that the problem occurs even if `bibtex-actions-symbols` is set to characters?

Also, why does only `bibtex-actions-link-symbol` have a default `defcustom`?

By the way @mclearc, how did you even come across the package? It's not even on melpa yet due to lack of battle testing (like this case here). Were you searching for icon support in Marginalia? I'm glad you find it useful!

@bdarcus re: biblio module in Doom, I agree, but I'd wait until after the biblio PR and the selectrum PR are merged, since this is kind of out of scope for both of them.

**Comment by bdarcus** [comment] 2021-07-07 18:39
@iyefrat 

> My best guess is that this conflicts somehow with the affixation-function logic in bibtex-actions-read.

Probably, though it seems odd to me.

> I assume that this doesn't really have to do with icons, and that the problem occurs even if bibtex-actions-symbols is set to characters?

What's the answer to this question @mclearc?

> Also, why does only bibtex-actions-link-symbol have a default defcustom?

I submitted a PR awhile back to add this to bibtex-completion, and remove it from here.

But it's unmerged ATM, partly because I got stuck on one piece of it.

https://github.com/tmalsburg/helm-bibtex/pull/366

> @bdarcus re: biblio module in Doom, I agree, but I'd wait until after the biblio PR and the selectrum PR are merged, since this is kind of out of scope for both of them.

No problem at all.

**Comment by mclearc** [comment] 2021-07-07 18:42
> I assume that this doesn't really have to do with icons, and that the problem occurs even if bibtex-actions-symbols is set to characters?

Yeah - if I have `all-the-icons-completion-mode` enabled there are no columns even if it is set to characters.

@iyefrat -- I'm not entirely sure how I found your package but I think it was via reading issues on marginalia awhile back. Thanks for putting the code together! I'm happy to test things out as you develop it.

**Comment by iyefrat** [comment] 2021-07-07 19:12
> So maybe it's too aggressive?
@bdarcus I'm not sure, I'll have to try and mess around with it, probably over the weekend. I'll report back if I figure anything out.

**Comment by bdarcus** [comment] 2021-07-08 12:32
I'm going to close this for now, since I doubt the problem is here.

**Closed by bdarcus** 2021-07-08 12:32 UTC
Labels: bug

**Comment by bdarcus** [comment] 2021-07-26 17:36
@iyefrat - any update on this? I still see issues with my affixations.

**Comment by bdarcus** [comment] 2021-07-26 18:02
Though, come to think of it, I don't think I have `+icons` on.

**Comment by iyefrat** [comment] 2021-07-26 22:35
Sorry, I haven't had time to look into this yet, but thanks for reminding me.

**Comment by bdarcus** [comment] 2021-07-27 21:30
Here's a screenshot of what I see ATM that prompted me to ask. I'm not certain this is related to your package, but it might be.

![Screenshot from 2021-07-27 17-27-23](https://user-images.githubusercontent.com/1134/127229831-a64d6807-57e7-4039-9c9b-b9cd3695be83.png)

**Comment by mclearc** [comment] 2021-10-06 20:12
@bdarcus  I can confirm that this still doesn't work for me.
